name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # enable maybe expressions
  ERL_AFLAGS: -enable-feature all

jobs:

  build:
    strategy:
      matrix:
        erlvsn: [25, 26]

    runs-on: ubuntu-latest

    container:
      image: erlang:${{ matrix.erlvsn }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
